viewer: viewer.o
	g++ -std=c++14 -o test viewer.o -framework OpenGL `pkg-config --static --libs glfw3`
viewer.o: viewer.cpp
	g++ -std=c++14 -c viewer.cpp -framework OpenGL `pkg-config --static --libs glfw3`

clean:
	rm viewer viewer.o